services:
  php-environment:
    container_name: moneyhub-apache
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8001:80
  db:
    container_name: moneyhub-db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: moneyhub
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASS
    ports:
      - "9906:3306"